### ISSUE TITLE
Examples Dropdown Still Not Working on Chrome

### ISSUE THREAD

**Issue by WalkerCodeRanger** [Whiley/WhileyLabs#9]
I see issue #5 reported a bug with the examples dropdown in Chrome and a "fix" was merged. The dropdown still isn't working in Chrome both on http://whileylabs.com/ and when I clone the repo and run locally with `ant run` on the "develop" branch. It is working in IE for me.

**Comment by DavePearce** [comment]
Hey Jeff,

Interesting.  It's possible the fix has been lost somehow along the way.  Yes, I agree with you its not working.

D

**Comment by DavePearce** [comment]
Hey Jeff,

Ok, have put through a possible fix currently on WhileyWeb/develop branch.  If you're happy that works I'll publish and launch to whileylabs.com

Cheers!

Dave

**Comment by WalkerCodeRanger** [comment]
Yes, that works. Feel free to close this issue once you publish to http://whileylabs.com

**Comment by DavePearce** [comment]
Yup, done now.
